[Feat] 인증/인가 구현과 관리자 로그인 구현
boostcampwm-2024/web12-MafiaCamp pull request #161
Opened 2024-11-20 07:30 UTC by 0Chord

## ☑️ 개발 유형

- [ ] Front-end
- [x] Back-end

## ✔️ PR 유형

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 기존 기능에 영향을 주지 않는 변경사항 (Ex. 오타 수정, 탭 사이즈 변경, 변수명 변경, 코드 리팩토링 등)
- [ ] 주석 관련 작업
- [ ] 문서 관련 작업
- [ ] 테스트 추가 혹은 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 📝 작업 내용

이번 PR에서 작업한 내용을 간략히 설명해주세요.

```
@Injectable()
export class UserDetailJwtGuard implements CanActivate {

  constructor(
    @Inject(TOKEN_VERIFY_USECASE)
    private readonly tokenVerifyUsecase: TokenVerifyUsecase,
  ) {
  }

  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();
    const accessToken = this.extractToken(request);
    const payload = this.tokenVerifyUsecase.verify(accessToken);
    const bodyUserId = request.body?.userId;
    const paramUserId = request.params?.userId;
    const queryUserId = request.query?.userId;
    this.verifyUserId(bodyUserId, payload, paramUserId, queryUserId);

    return true;
  }

  private verifyUserId(bodyUserId, payload: Record<string, any>, paramUserId, queryUserId) {
    if (bodyUserId && payload.userId !== bodyUserId) {
      throw new UnauthorizedUserException();
    }

    if (paramUserId && payload.userId !== paramUserId) {
      throw new UnauthorizedUserException();
    }

    if (queryUserId && payload.userId !== queryUserId) {
      throw new UnauthorizedUserException();
    }

    if (!queryUserId && !paramUserId && !bodyUserId) {
      throw new UnauthorizedUserException();
    }
  }

  private extractToken(request): string {
    const [type, token] = request.headers.authorization?.split(' ') ?? [];
    if (type !== 'Bearer') {
      throw new UnauthorizedUserException();
    }
    return token;
  }

}
```
- [x] JWT를 통한 인증 인가를 구현했습니다. 직접 가드를 만들어 인증 토큰 속의 userId와 request Body속의 userId가 일치하는지 확인하는 작업을 진행했습니다. JWT는 AccessToken으로만 구성되며 AccessToken의 만료시간은 6시간으로 구성했습니다.
- [x] 관리자용 회원가입 API와 로그인 API를 구현했습니다. 관련 API는 API 문서에 적어놓겠습니다.
- [x] 유저 정보 가져오는 API를 구현했습니다. 관련 API는 API 문서에 적어놓았습니다.
## #️⃣ Related Issue

해당 Pull Request과 관련된 Issue Link를 작성해 주세요
#157 #158 #169

2024-11-20 13:07 UTC, HyunJinNo submitted a review, later dismissed
수고하셨습니다.

2024-11-20 14:44 UTC, HyunJinNo submitted a review, later dismissed

2024-11-20 14:52 UTC, HyunJinNo requested changes

2024-11-20 14:52 UTC, HyunJinNo commented on BE/src/common/error/exception.code.ts
> -  UNAUTHORIZED_USER_EXCEPTION: 1013,
예외 코드 숫자가 중복됐다는 의미여서, 해당 예외 코드 종류를 삭제하는 것이 아니라 예외 코드의 숫자를 중복되지 않게 수정해야 합니다.

2024-11-20 14:56 UTC, 0Chord commented on BE/src/auth/guard/user-detail.jwt.guard.ts
> +    this.verifyUserId(bodyUserId, payload, paramUserId, queryUserId);
네 맞습니다. RequestParam, RequestQuery, RequestBody에 해당 userId가 있는지 그리고 그 유저 Id가 token의 payload와 일치하는지 검증하는 메서드입니다

2024-11-20 14:56 UTC, 0Chord commented on BE/src/auth/usecase/token.provide.usecase.ts
> +  generateToken(payload: Record<string, any>): string;
저도 그게 더 좋은 것 같습니다.

2024-11-20 14:56 UTC, 0Chord commented on BE/src/user/controller/auth.controller.ts
> +    return;
return을 안했을 때 res 응답이 잘 안갔는데 한번 더 확인해봐야겠습니다.

2024-11-20 14:56 UTC, 0Chord commented on BE/src/user/controller/user.controller.ts
> +    return;
return을 안하면 동작을 안하고 계속 Pending처럼 남아있었는데 한번 확인해보겠습니다.

2024-11-20 14:56 UTC, 0Chord commented on BE/src/user/dto/admin-login.request.ts
> +}
해당 파일에서 사용안한게 문제인 것 같습니다. 추가해놓겠습니다

2024-11-20 14:56 UTC, 0Chord commented on BE/src/user/entity/user.entity.ts
>    private constructor(
typeORM 저런 안좋은 점이 있었군요. JPA 방식대로 하다보니 저 특성을 고려하지 않았던 것 같습니다

2024-11-20 14:56 UTC, 0Chord commented on BE/src/user/entity/user.entity.ts
> +    return new UserEntity(email, nickname, password, oAuthId, 0, new Date());
몰라서 안했었는데 다음부터는 저거로 하는게 좋아보입니다

2024-11-20 15:23 UTC, HyunJinNo approved these changes

2024-11-20 15:24 UTC, 0Chord commented on BE/src/common/error/exception.code.ts
> -  UNAUTHORIZED_USER_EXCEPTION: 1013,
이 부분 다시 살려놓았습니다. 순차적으로 머지를 안하니 컨플릭트가 난 것 같네요

2024-11-21 01:51 UTC, HyunJinNo submitted a review, later dismissed
확인했습니다.

2024-11-21 02:29 UTC, Gyeongsu1997 submitted a review, later dismissed
확인했습니다

2024-11-21 02:29 UTC, Gyeongsu1997 commented on BE/src/user/dto/admin-login.request.ts
> +  email: string;
class-validator 중 Matches를 이용해 정규식으로 이메일 형태를 검증하는 게 좋아보입니다.

2024-11-21 02:29 UTC, Gyeongsu1997 commented on BE/src/user/user.service.ts
> +    const payload = this.tokenVerifyUsecase.verify(token);
토큰에 대한 검증은 일관성있게 컨트롤러에서 Guard로 하는 게 나아보입니다.

2024-11-21 02:59 UTC, simjaesung approved these changes
고생하셨습니다! 코드들 보면서 학습을 하느라 승인이 늦었네요..!

2024-11-21 02:59 UTC, simjaesung commented on BE/src/common/logger/sanitize.data.ts
> +  const sensitiveFields = ['password', 'token', 'secret','code'];
함수명을 해석하면 `데이터를 소독하다` 이군요!
로그에 민감한 정보를 남기지 않기위해 이런 과정이 필요하다는 것을 처음 알았습니다! 또 하나 배워갑니다!

2024-11-21 02:59 UTC, simjaesung commented on BE/src/user/controller/user.controller.ts
> +    return;
return을 통해 명시적으로 반환하여 완료 상태를 알려주는 것이 좋은 방법이라고 생각합니다. 

현재 함수에서 호출되는 비동기 함수들에도 반환값이 명시되어있지 않아 암묵적으로 `Promise<undefined>`를 반환할 가능성이 있어 보이네요.

2024-11-21 02:59 UTC, simjaesung commented on BE/src/user/entity/user.entity.ts
>    private constructor(
좋은 거 하나 배워갑니다..!

2024-11-21 03:00 UTC, HyunJinNo approved these changes

2024-11-21 03:01 UTC, 0Chord commented on BE/src/user/user.service.ts
> +    const payload = this.tokenVerifyUsecase.verify(token);
토큰에 대한 검증보다는 토큰의 페이로드에서 해당 유저의 userId를
가져오기 위함이라 가드에서 처리하지 않고 사비스 계층에서 처리했습니다

2024-11-21 03:15 UTC, simjaesung submitted a review, later dismissed

2024-11-21 03:47 UTC, Gyeongsu1997 approved these changes

2024-11-21 03:56 UTC, Gyeongsu1997 approved these changes

2024-11-21 04:00 UTC, simjaesung approved these changes

2024-11-21 04:07 UTC, HyunJinNo approved these changes

2024-11-21 04:07 UTC, merged