[Feat] OpenVidu NestJS 환경설정 및 SSL 인증서 발급
boostcampwm-2024/web12-MafiaCamp pull request #87
Opened 2024-11-06 00:53 UTC by simjaesung

## ☑️ 개발 유형

- [ ] Front-end
- [x] Back-end

## ✔️ PR 유형

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 기존 기능에 영향을 주지 않는 변경사항 (Ex. 오타 수정, 탭 사이즈 변경, 변수명 변경, 코드 리팩토링 등)
- [ ] 주석 관련 작업
- [ ] 문서 관련 작업
- [ ] 테스트 추가 혹은 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 📝 작업 내용

코드적으로 내용이 많지 않습니다. 
ssl 인증 관련해서 겪은 문제들을 기록해두었습니다.

- [x] openvidu 모듈 생성
- [x] local ssl 인증서 발급 및 https 연결 설정
- [x] openvidu 연결 테스트

## #️⃣ Related Issue

#5 
#8 

<br/>

## BE openvidu 관련 `.env` 파일

```yaml
OPENVIDU_URL=https://localhost:4443
OPENVIDU_SECRET=MAFIA_GAME
NODE_TLS_REJECT_UNAUTHORIZED=0
```
상단 내용을 BE .env 파일에 추가해두시면 됩니다.

<br/>

## 발생한 문제

### 1. Nest 인증 문제

자체 서명된 인증서는 브라우저나 HTTP 클라이언트에서 기본적으로 신뢰하지 않기 때문에, `NODE_TLS_REJECT_UNAUTHORIZED=0` 설정을 통해 SSL 검증을 건너뛰도록 해야 하는 상황이 발생했었습니다.

제가 사용한 mkcert 또한 자체 서명된 인증서로 CA에서 발급된게 아니기에, 기본적으로 신뢰할 수 있는 인증서로 간주되지 않는다고 합니다. 이를 해결하기 위해 **로컬 시스템에 자체 서명된 인증서를 신뢰할 수 있는 인증서로 등록**할 수 있습니다. 

다만, 이는 로컬 테스트 환경에서만 사용하기에 적합합니다.

<br/>

### mkcert CA 인증서 문제해결 방법

`mkcert`로 발급한 인증서를 Node.js에 SSL 인증서를 신뢰하도록 하기 위해 `NODE_EXTRA_CA_CERTS` 환경 변수를 설정해야 합니다. 이를 통해 Node.js가 `mkcert`의 자체 CA 인증서를 신뢰하게 할 수 있습니다.

**1. `mkcert` CA 경로 확인**

`mkcert`로 발급한 인증서의 CA 경로는 다음 명령어로 확인할 수 있습니다:

```bash
mkcert -CAROOT
```

이 명령을 실행하면 `mkcert` CA 인증서(`rootCA.pem`)가 위치한 경로가 표시됩니다.

- `~/Library/Application Support/mkcert` (macOS)
- `~/.local/share/mkcert` (Linux)
- `C:\\Users\\<username>\\AppData\\Local\\mkcert` (Windows)

<br/>

**2. `NODE_EXTRA_CA_CERTS` 환경 변수 설정**

`NODE_EXTRA_CA_CERTS` 환경 변수를 사용하여 Node.js가 `mkcert`의 루트 CA 인증서를 신뢰하도록 설정할 수 있습니다. 이 환경 변수는 Node.js가 추가로 신뢰해야 할 CA 인증서를 지정할 때 사용됩니다.

<br/>

**터미널에서 설정하기**

로컬 개발 환경에서 터미널에 다음과 같이 입력해 `NODE_EXTRA_CA_CERTS` 환경 변수를 설정할 수 있습니다.

```bash
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
```

위 명령을 실행하면, Node.js가 `mkcert`로 발급된 SSL 인증서를 신뢰하게 됩니다.

<br/>

**Windows 환경 설정**

Windows에서 `NODE_EXTRA_CA_CERTS` 환경 변수를 설정하는 방법은 다음과 같습니다.

```bash
set NODE_EXTRA_CA_CERTS=C:\\path\\to\\mkcert\\rootCA.pem
```

위 명령에서 `C:\\path\\to\\mkcert\\rootCA.pem` 부분을 실제 CA 인증서 경로로 변경해야한다고 합니다.

<br/>

**주의사항**

- **환경 변수 설정은 터미널 세션마다 적용**됩니다. 새로운 터미널 세션을 열 때마다 이 변수를 다시 설정해야 합니다.
- 로컬 환경에서만 사용하고, 배포 환경에서는 Let’s Encrypt와 같은 공인된 인증서를 사용하는 것이 좋습니다.

이렇게 설정하면 `httpsOptions`에 `mkcert`로 발급한 인증서를 사용하는 NestJS 애플리케이션이 SSL 검증 오류 없이 정상적으로 HTTPS 연결을 유지할 수 있습니다.

<br/>

### 2. SSL 캐시 conflict 문제

```yaml
2024-11-06 01:38:42 2024/11/05 16:38:42 [emerg] 575#575: the size 10485760 of shared memory zone "SSL" conflicts with already declared size 52428800 in /etc/nginx/vhost.d/default.conf:11
2024-11-06 01:38:42 nginx: [emerg] the size 10485760 of shared memory zone "SSL" conflicts with already declared size 52428800 in /etc/nginx/vhost.d/default.conf:11
```

Nginx log중 일부입니다. 

발생하는 `shared memory zone 'SSL' conflicts with already declared size`  오류는 `ssl_session_cache shared:SSL:10m;` 설정이 Nginx 설정 파일 내 여러 곳에 중복되어 있거나, 동일한 이름의 공유 메모리 영역(`SSL`)이 다른 크기로 설정되어 있을 때 발생하는 문제였습니다.

Nginx 가 컨테이너 내에서 실행중이기에, 해당 컨테이너 내부에서 중복으로 선언되었는지 확인했습니다.

<img width="543" alt="image" src="https://github.com/user-attachments/assets/3985acaa-abcd-4c4c-b8c1-7ee0c46e562a">

실제로 2곳에 중복으로 선언되어있었습니다.

둘 중 하나를 주석처리하여 하려했지만,

`conf.d` 폴더내에 있는 설정파일은 도커 실행 시 자동으로 재생성되었고,

`vhost.d` 폴더 내에 넣어둔 설정파일을 주석처리할 경우 서버가 실행되지 않는 문제가 있었습니다.

우선 동작에는 영향이 가지 않아 두었지만, 추후 문제가 있을 수 있어 우선 기록해둡니다.

2024-11-06 08:13 UTC, HyunJinNo approved these changes
수고하셨습니다.

2024-11-06 09:45 UTC, 0Chord reviewed
고생하셨습니다

2024-11-06 09:45 UTC, 0Chord commented on BE/src/openvidu/openvidu.service.ts
> +}
Openvidu가 아닌 MediaSoup을 사용하여 구축하는 상황도 가정할 수 있습니다.
인터페이스를 통해 추상화를 진행하여 Module에서 의존성 주입을 해 객체지향적인 설계를 진행할 수 있습니다.

2024-11-06 13:30 UTC, simjaesung commented on BE/src/openvidu/openvidu.service.ts
> +}
@0Chord 영현님 pr 참고하여 코드 작성해보겠습니다!

2024-11-06 13:34 UTC, HyunJinNo requested changes
앗, 다시 확인해보니 브랜치 이름이 BE_feature/#5 가 아니라 BE_featuer/#5로 오타를 내셨네요. 수정 부탁드립니다.

2024-11-07 01:36 UTC, HyunJinNo approved these changes

2024-11-07 02:39 UTC, 0Chord submitted a review, later dismissed

2024-11-07 02:50 UTC, Gyeongsu1997 commented
mkcert 인증서를 개발 환경에서 사용하기 위해서는 NODE_TLS_REJECT_UNAUTHORIZED=0 설정과 NODE_EXTRA_CA_CERTS 환경 변수 설정을 둘다 해야한다는 말인가요? 고생하셨습니다.

2024-11-07 02:50 UTC, Gyeongsu1997 submitted a review, later dismissed

2024-11-07 03:01 UTC, HyunJinNo approved these changes

2024-11-07 03:01 UTC, 0Chord approved these changes

2024-11-07 03:02 UTC, Gyeongsu1997 approved these changes

2024-11-07 03:03 UTC, simjaesung commented
@Gyeongsu1997 
- NODE_TLS_REJECT_UNAUTHORIZED=0 설정 같은 경우는 Node.js 환경 변수로 SSL 검증을 무시해주는 설정
- NODE_EXTRA_CA_CERTS 설정은 Node.js가 mkcert의 루트 CA 인증서를 신뢰하도록 설정하는 것입니다.

결론은 둘 중 하나만 하면 됩니다!

2024-11-07 03:03 UTC, merged